server:
  port: 8013
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/,http://localhost:7001/eureka/
spring:
  application:
    name: shop-cart-api #配置注册中心地址