eureka:
  instance:
    hostname: locahost #指定主机地址
  client:
    fetch-registry: false #指定是否要冲注册中心获取服务(注册中心不需要开启)
    register-with-eureka: false #指定是否要注册到注册中心中去(注册中心不需要开启)
  service-url:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8001

#  server:
#    enable-self-preservation: false #关闭保护模式
